account/urls.py
from django.urls import path, include
from account import views
from appoint_app.views import dashboard, home, terms
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('export_user_payments_pdf/', views.export_user_payments_pdf, name='export_user_payments_pdf'),
    path('export_admin_all_payments_pdf/', views.export_admin_all_payments_pdf, name='export_admin_all_payments_pdf'),
    path('account/export_appointment_pdf/<str:appointment_id>/', views.export_appointment_pdf, name='export_appointment_pdf'),
    
    path('toggle-dark-mode/', views.toggle_dark_mode, name='toggle_dark_mode'),
    path('delete_account_confirmation/', views.delete_account_confirmation, name='delete_account_confirmation'),
    
    path('export/appointments_payments/pdf/', views.export_appointments_payments_pdf, name='export_appointments_payments_pdf'),
    
    path('doctor-otp-verification/', views.doctor_otp_verification, name='doctor_otp_verification'),
    path('admin-otp-verification/', views.admin_otp_verification, name='admin_otp_verification'),

    path('update-next-kin/<str:patient_username>/', views.update_patient_next_kin, name='update-next-kin'),
    path('update-patient-next-kin/<str:patient_username>/', views.update_patient_next_kin, name='update-patient-next-kin'),
    path('delete-next-of-kin/', views.delete_next_of_kin, name='delete-next-of-kin'),
    
    path("all-payments/", views.view_payments_patient, name='all-payments'),
    path("user-payments/", views.view_all_payments, name='user-payments'),
    path("manage-user-payments/", views.all_payments, name='manage-user-payments'),
    
    # path('create-appointment/next-of-kin/', views.create_appointment_next_of_kin, name='create-appointment-next-of-kin'),
    
    path("approved-appointments/", views.approved_appointments, name='approved-appointments'),
    path("create-appointment-patient/", views.create_appointment_patient, name='create-appointment-patient'),
    path("view-appointments-manage/", views.view_appointments_manage, name='view-appointments-manage'),
    path("appointments-list/", views.all_appointments, name='appointments_list'),
    path("appointments-list-doctor/", views.all_appointments_doctor, name='appointments_list_doctor'),
    path("view-appointments/", views.view_appointments, name='view-appointments'),
    path("view-all-appointments/", views.view_all_appointments, name='view-all-appointments'),
    path("view-all-appointments-doctor/", views.view_all_appointments_doctor, name='view-all-appointments-doctor'),
    path("view-appointment-patient/<str:appointment_id>/", views.view_appointment_patient, name='view-appointment-patient'),
    path("view-appointment/<str:appointment_id>/", views.view_appointment, name='view-appointment'),
    path("close-appointment/<str:appointment_id>/", views.close_appointment, name='close-appointment'),
    path("close-appointment-doctor/<str:appointment_id>/", views.close_appointment_doctor, name='close-appointment-doctor'),
    path("closed-appointments/", views.closed_appointments, name='closed-appointments'),
    path("cancel-appointment/<str:appointment_id>/", views.cancel_appointment, name='cancel-appointment'),
    path("cancel-patient-appointment/<str:appointment_id>/", views.cancel_patient_appointment, name='cancel-patient-appointment'),
    path("delete-appointment/<str:appointment_id>/", views.delete_appointment, name='delete-appointment'),
    path("delete-patient-appointment/<str:appointment_id>/", views.delete_patient_appointment, name='delete-patient-appointment'),
    path("video-call-patient/", views.video_call_patient, name='video-call-patient'),
    path("vide-call/", views.video_call, name='video-call'),
    
    path("", dashboard, name='dashboard'),
    path("home/", home, name='home'), 
    path('terms/', terms, name='terms'),
    
    path("update-doctor-profile/<str:doctor_username>/", views.update_doctor_profile, name='update-doctor-profile'),
    path("update-admin-profile/<str:admin_username>/", views.update_admin_profile, name='update-admin-profile'),
    path("update-patient-profile/<str:patient_username>/", views.update_patient_profile, name='update-patient-profile'),
    
    path('admins-portal/', TemplateView.as_view(template_name='appoint_app/admins_portal.html'), name='admins_portal'),
    path('doctors-portal/', TemplateView.as_view(template_name='appoint_app/doctors_portal.html'), name='doctors_portal'),
    path('student-patients-portal/', TemplateView.as_view(template_name='appoint_app/student_patients_portal.html'), name='student_patients_portal'),
    path('staff-patients-portal/', TemplateView.as_view(template_name='appoint_app/staff_patients_portal.html'), name='staff_patients_portal'),
     
    path('register-doctor/', views.register_doctor, name='register-doctor'),
    path('register-patient/', views.register_patient, name='register-patient'),
    path('register-patient-admin/', views.register_patient_admin, name='register-patient-admin'),
    path('register-admin/', views.register_admin, name='register-admin'),
    path("login/", views.login_user, name='login'),
    path("logout/", views.logout_user, name='logout'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    
    path('password-change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password-change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    
    path('check_email_exists/', views.check_email_exists, name='check_email_exists'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset_form.html'), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset/complete/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),

    path("", include('django.contrib.auth.urls')),
]

appoint/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from account import views


urlpatterns = [
    path("__reload__/", include("django_browser_reload.urls")),
    path('admin/', admin.site.urls),
    path("", include('appoint_app.urls')),
    path("account/", include('account.urls')),
    path('secure-appoint-pay/', include('payments.urls')),
    
    path('password-change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password-change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    
    path('check_email_exists/', views.check_email_exists, name='check_email_exists'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='appoint_app/password_reset_form.html'), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='appoint_app/password_reset_done.html'), name='password_reset_done'), 
    path('password-reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='appoint_app/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset/complete/', auth_views.PasswordResetCompleteView.as_view(template_name='appoint_app/password_reset_complete.html'), name='password_reset_complete'),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.STATIC_ROOT)

appoint_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('admin/logout/', views.logout_view, name='logout'),
    path("", views.dashboard, name='dashboard'),
    path("home/", views.home, name='home'), 
    path('terms/', views.terms, name='terms'),
]

account/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.utils import timezone
import random
import string
from phonenumber_field.modelfields import PhoneNumberField
from django.contrib.auth.models import AbstractUser
from django.db.models import Q


# Create a Custom User Model   
class User(AbstractUser):
    GENDER_CHOICES = [
        ('Male', 'Male'),
        ('Female', 'Female'),
        ('Other', 'Other'),
    ]
   
    PATIENT_TYPE_CHOICES = [
        ('', '-----'),
        ('Student', 'Student'),
        ('Staff', 'Staff'),
    ]
    
    SPECIALIZATION_CHOICES = [
        ('', '----------'),
        ('Dentistry', 'Dentistry'),
        ('Pharmacy', 'Pharmacy'),       
        ('Consultation', 'Consultation'),
        ('Flu Treatment', 'Flu Treatment'),
        ('ENT', 'Ear, Nose, and Throat (ENT)'),
        ('Reproductive Health', 'Reproductive Health'),
        ('Mental Health', 'Mental Health'),
        ('Physiotherapy', 'Physiotherapy'),
        ('Covid-Screening', 'Covid-19 Screening'),
        ('VCT', 'HIV Counselling & Treatment'),
        ('Laboratory', 'Laboratory Tests'),
        ('Referral', 'Referral'),
        ('Other issue', 'Other issue'),]
    
    is_Student_Patient = models.BooleanField(default=False)
    is_Staff_Patient = models.BooleanField(default=False)
    has_next_of_kin = models.BooleanField(default=False)
    active = models.BooleanField(default=True)
    next_of_kin = models.ForeignKey('NextOfKin', on_delete=models.CASCADE, blank=True, null=True)
    is_Doctor = models.BooleanField(default=False)
    specialization = models.CharField(max_length=19, blank=False, choices=SPECIALIZATION_CHOICES)
    profile_photo = models.ImageField(upload_to='Profile-photos/', null=True, blank=True)
    patient_type = models.CharField(max_length=50, choices=PATIENT_TYPE_CHOICES)
    patient_id = models.CharField(max_length=15, unique=True, blank=True, null=True)
    first_name = models.CharField(max_length=50, blank=True, null=True)
    last_name = models.CharField(max_length=50, blank=True, null=True)
    gender = models.CharField(max_length=10, choices=GENDER_CHOICES, default="")
    phone_number = PhoneNumberField(max_length=13, blank=True, null=True, unique=True)
    email = models.EmailField(unique=True)
    username = models.CharField(max_length=50, unique=True)
    password = models.CharField(max_length=128)
    
    last_login = models.DateTimeField(null=True, blank=True)
    last_logout = models.DateTimeField(null=True, blank=True)

    def set_last_login(self):
        self.last_login = timezone.now()
        self.save(update_fields=['last_login'])

    def set_last_logout(self):
        self.last_logout = timezone.now()
        self.save(update_fields=['last_logout'])
    
    def populate_username(self):
        if self.patient_id:
            self.username = self.patient_id.username
            self.save()
    
    def next_of_kin_name(self):
        if self.has_next_of_kin:
            try:
                next_of_kin = NextOfKin.objects.get(related_patient=self)
                return f"{next_of_kin.kin_fname} {next_of_kin.kin_lname}"
            except NextOfKin.DoesNotExist:
                return "None"
        else:
            return "None"
        
    # Meta class to set metadata options
    class Meta:
        verbose_name = 'User'
        verbose_name_plural = 'Users'
    
    def __str__(self):
        return f"{self.first_name} {self.last_name}"


# Create a model for Next of Kin(for a Patient)
class NextOfKin(models.Model):
    RELATIONSHIP_CHOICES = [
        ('', '----------'),
        ('Brother', 'Brother'),
        ('Sister', 'Sister'),
        ('Son', 'Son'),
        ('Daughter', 'Daughter'),
        ('Mother', 'Mother'),
        ('Father', 'Father'),
        ('Aunt', 'Aunt'),
        ('Uncle', 'Uncle'),
        ('Niece', 'Niece'),
        ('Nephew', 'Nephew'),
        ('Cousin', 'Cousin'),
        ('Other close Relative', 'Other close Relative'),
        ('Wife', 'Wife'),
        ('Husband', 'Husband'),
        ('Guardian', 'Guardian'),
    ]

    kin_fname = models.CharField(max_length=50)
    kin_lname = models.CharField(max_length=50)
    related_patient = models.ForeignKey(
    User,
    verbose_name='Related Patient',
    on_delete=models.CASCADE,
    limit_choices_to=Q(is_Student_Patient=True) | Q(is_Staff_Patient=True)
)
    relationship = models.CharField(max_length=50, choices=RELATIONSHIP_CHOICES)
    kin_phone = PhoneNumberField(max_length=13, blank=True, null=True, unique=False)

    def __str__(self):
        return f"{self.kin_fname} {self.kin_lname}"
    
    class Meta:
        verbose_name = "Next of Kin"
        verbose_name_plural = "Next of Kins"


# Create a model for Patient ID(Student & Staff)
class ID(models.Model):
    PATIENT_TYPE_CHOICES = [
        ('Student', 'Student'),
        ('Staff', 'Staff'),
    ]
    patient_id = models.CharField(max_length=15, unique=True)
    patient_type = models.CharField(max_length=50, choices=PATIENT_TYPE_CHOICES)
    registered = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.patient_type} ID: {self.patient_id}"
    
    class Meta:
        verbose_name = "Patient ID"
        verbose_name_plural = "Patient IDs"


# Create a method to generate a random appointment ID
def generate_appointment_id():
    alphanumeric = string.ascii_letters + string.digits
    return ''.join(random.choices(alphanumeric, k=6))


# Create a model for Appointment
class Appointment(models.Model):
    APPOINTMENT_AREA_CHOICES = (
        ('', '----------'),
        ('Dentistry', 'Dentistry'),
        ('Pharmacy', 'Pharmacy'),       
        ('Consultation', 'Consultation'),
        ('Flu Treatment', 'Flu Treatment'),
        ('ENT', 'Ear, Nose, and Throat (ENT)'),
        ('Reproductive Health', 'Reproductive Health'),
        ('Mental Health', 'Mental Health'),
        ('Physiotherapy', 'Physiotherapy'),
        ('Covid-Screening', 'Covid-19 Screening'),
        ('VCT', 'HIV Counselling & Treatment'),
        ('Laboratory', 'Laboratory Tests'),
        ('Referral', 'Referral'),
        ('Other issue', 'Other issue'),
    )
     
    APPOINTMENT_STATUS_CHOICES = (
        ('', '-----'),
        ('Failed', 'Failed'),
        ('Scheduled', 'Scheduled'),
        ('Canceled', 'Canceled'),
        ('Completed', 'Completed'),    
    )
    
    FOR_CHOICES = [
        ('', '-----'),
        ('self', 'Self'),
        ('next_of_kin', 'Next of Kin'),
    ]
    
    RESOLVED_CHOICES = [
    (True, 'Yes'),
    (False, 'No'),]
    
    PAYMENT_CHOICES = [
    (True, 'Verified'),
    (False, 'N/A'),]
    
    payment = models.BooleanField('Payment', default=False, blank=True, null=True, choices=PAYMENT_CHOICES)
    appoint_id = models.CharField('Appointment ID', primary_key=True, max_length=6, default=generate_appointment_id, editable=False)
    appoint_area = models.CharField('Area', max_length=19, blank=False, choices=APPOINTMENT_AREA_CHOICES)
    appointee = models.ForeignKey(User, on_delete=models.CASCADE, related_name='patients', blank=False)
    appointed_doctor = models.ForeignKey(User, blank=True, null=True, related_name="Doctors", on_delete=models.SET_NULL)
    book_time = models.DateTimeField('Booked on', default=timezone.now, editable=False)
    approve_date = models.DateTimeField('Approved on', blank=True, null=True)
    appoint_time = models.DateTimeField('Appointed Date', blank=True, null=True)
    doctor_remarks = models.CharField('Remarks', max_length=100, blank=True, null=True)
    is_resolved = models.BooleanField('Is resolved', default=False, blank=True, null=True, choices=RESOLVED_CHOICES)
    close_date = models.DateTimeField('Closed on', blank=True, null=True)
    appoint_status = models.CharField('Status', max_length=10, choices=APPOINTMENT_STATUS_CHOICES, blank=False)

    # Save method to set the book time & appoint ID
    def save(self, *args, **kwargs):
        if not self.pk:  # Only set the book time if it's a new appointment
            self.book_time = timezone.now()
        self.full_clean()  # Validate model fields before saving
        super().save(*args, **kwargs)  # Call the "real" save() method

    def __str__(self):
        return self.appoint_id


# Create a model for OTP(One Time Password)    
class OTP(models.Model):
    otp_code = models.CharField(max_length=6)
    otp_created = models.DateTimeField(default=timezone.now)
    otp_verified = models.BooleanField(default=False)
    for_email = models.EmailField(null=True, blank=True, default="")

    @classmethod
    def generate_otp(cls):
        return ''.join(random.choices('0123456789', k=6))
    class Meta:
        verbose_name = "OTP"
        verbose_name_plural = "OTPs"
    

appoint_app/templates/appoint_app/cancel_appointment.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cancel Confirmation@Admin</title>
    <style>
        body {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 80vh;
            margin: 0;
            background-color: #f0f0f0;
        }
        .container {
            text-align: center;
            padding: 30px;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        }
        .btn-delete {
            background-color: #e53e3e;
            color: #fff;
            border: none;
            padding: 10px 15px;
            margin-right: 10px;
            border-radius: 9px;
            cursor: pointer;
            margin-bottom: 5px;
        }
        .btn-delete:hover {
            background-color: #c53030;
        }
        .btn-cancel {
            background-color: #3182ce;
            color: #fff;
            border: none;
            padding: 10px 15px;
            border-radius: 9px;
            cursor: pointer;
            margin-bottom: 5px;
        }
        .btn-cancel:hover {
            background-color: #2c5282;
        }
    </style>
	<link rel="stylesheet" href="{% static 'appoint_app/css/messages.css' %}">
</head>
<body>
    <div class="container">
        <div class="text-center pb-2">
            <img src="{% static 'appoint_app/images/appointment_doctor.png' %}" alt="Logo" style="width: 43px; height: 43px;">
        </div>
        <h2 style="font-size: 21px; font-family:'Times New Roman', Times, serif;">Confirm Appointment Cancel</h2>
        <p>Are you sure you want to cancel the appointment?</p>
        <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn-delete" style="text-decoration: none;">Yes</button>
            <a href="/" class="btn-cancel" style="text-decoration: none;">No</a>
        </form>
    </div>
</body>
</html>

appoint_app/templates/appoint_app/password_reset_email.html
You asked for password reset for the email {{ email }}. Follow the link below:
{{ protocol }}://{{ domain }}{% url "password_reset_confirm" uidb64=uid 
token=token %}
Your Username, in case you've forgotten: {{ user.get_username }}

appoint_app/templates/appoint_app/update_admin_profile.html
{% if request.user.is_authenticated%}
{% load static tailwind_tags %}
<!DOCTYPE html>
<html class="h-full bg-violet-50" lang="en">
	<head>
        <title>Doctor Appointment | Update Profile@Admin</title>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <meta http-equiv="X-UA-Compatible" content="ie=edge">
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" />
            <link rel="stylesheet" href="{% static 'appoint_app/css/messages.css' %}">
			<script src="{% static 'appoint_app/js/dob_script.js' %}"></script>
        {% tailwind_css %}
	</head>
	<body>
		<div class="flex min-h-full flex-col justify-center px-10 py-10 lg:px-8">
            <div class="message-container">
				{% if messages %}
				{% for message in messages %}
				<div class="message {% if message.tags == 'success' %}message-success{% elif message.tags == 'error' %}message-error{% endif %}">
					{{ message }}
				</div>
				{% endfor %}
				{% endif %}
			</div>	
			<div class="sm:mx-auto sm:w-full sm:max-w-sm">
			  <img class="mx-auto h-10 top-1 w-auto" src="{% static 'appoint_app/images/appointment_doctor.png' %}" alt="Logo">
			  <h2 class="mt-2 text-center text-2xl font-bold leading-9 tracking-tight text-blue-800">Update Profile</h2>
			</div>
		  
			<div class="update-admin-form-admin mt-1 sm:mx-auto sm:w-full sm:max-w-sm">
				<form action="{% url 'update-admin-profile' admin_username=profile.username %}" method="POST" enctype="multipart/form-data">
					{% csrf_token %}
					{% for field in form %}
					<div>
						<label class="form-label">{{ field.label }}</label>
						{% if field.name == 'profile_photo' %}
						<div class="flex flex-col items-center mt-2 justify-center relative">
							{% if profile.profile_photo %}
							<img src="{{ profile.profile_photo.url }}" alt="+" class="w-24 h-24 rounded-full mt-2 cursor-pointer bg-violet-100" onclick="choosePhoto()">
							{% else %}
							<label for="id_profile_photo" class="w-full rounded-full border-1 border-none cursor-pointer flex  items-center justify-center font-semibold text-red-700">Choose Photo</label>
							{% endif %}
							<input type="file" id="id_profile_photo" name="profile_photo" accept="image/*" class="hidden" onchange="showPreview(this)">
						</div>
						{% else %}
						{{ field }}
						{% endif %}
						{% if field.errors %}
						<div class="text-red-500 text-sm mt-1 font-semibold">
							{% for error in field.errors %}
							{{ error }}
							{% endfor %}
						</div>
						{% endif %}
					</div>
					{% endfor %}
					<div class="mt-5 flex justify-center">
						<button type="submit" class="relative w-full border-0 py-1.5 items-center justify-center bg-gradient-to-r from-purple-500 to-blue-500 hover:from-purple-600 hover:to-blue-600 focus:outline-none focus:ring focus:ring-purple-300 active:bg-blue-700 rounded-full text-white font-semibold shadow-md transition duration-300 ease-in-out transform hover:scale-105">Update Profile</button>
					</div>
				</form>
				<p class="mt-5 mb-12 text-center text-sm text-gray-500">
					Back to
					<a href="/" class="font-semibold text-indigo-600 hover:text-indigo-500">Dashboard</a>
				</p>
			</div>	
			
		</div>
		<script src="{% static 'appoint_app/js/profile_photo.js' %}"></script>
		<script src="{% static 'appoint_app/js/register_patient.js' %}"></script>
	</body>
</html>
{% endif %}

appoint_app/templates/appoint_app/update_doctor_profile.html
{% if request.user.is_authenticated%}
{% load static tailwind_tags %}
<!DOCTYPE html>
<html class="h-full bg-violet-50" lang="en">
	<head>
        <title>Doctor Appointment | Update Profile@Doctor</title>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <meta http-equiv="X-UA-Compatible" content="ie=edge">
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" />
            <link rel="stylesheet" href="{% static 'appoint_app/css/messages.css' %}">
        {% tailwind_css %}
	</head>
	<body>
		<div class="flex min-h-full flex-col justify-center px-10 py-10 lg:px-8">
            <div class="message-container">
				{% if messages %}
				{% for message in messages %}
				<div class="message {% if message.tags == 'success' %}message-success{% elif message.tags == 'error' %}message-error{% endif %}">
					{{ message }}
				</div>
				{% endfor %}
				{% endif %}
			</div>	
			<div class="sm:mx-auto sm:w-full sm:max-w-sm">
			  <img class="mx-auto h-10 top-1 w-auto" src="{% static 'appoint_app/images/appointment_doctor.png' %}" alt="Logo">
			  <h2 class="mt-2 text-center text-2xl font-bold leading-9 tracking-tight text-blue-800">Update Profile</h2>
			</div>
		  
			<div class="update-profile-form-doctor mt-1 sm:mx-auto sm:w-full sm:max-w-sm">
				<form action="{% url 'update-doctor-profile' doctor_username=profile.username %}" method="POST" enctype="multipart/form-data">
					{% csrf_token %}
					{% for field in form %}
					<div>
						<label class="form-label">{{ field.label }}</label>
						{% if field.name == 'dob' %}
						<input type="date" name="{{ field.name }}" id="{{ field.id }}" value="{{ profile.dob|date:'Y-m-d' }}" class="block w-full rounded-full border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6">
						{% elif field.name == 'profile_photo' %}
						<div class="flex flex-col items-center mt-2 justify-center relative">
							{% if profile.profile_photo %}
							<img src="{{ profile.profile_photo.url }}" alt="+" class="w-24 h-24 rounded-full mt-2 cursor-pointer bg-violet-100" onclick="choosePhoto()">
							{% else %}
							<label for="id_profile_photo" class="w-full rounded-full border-1 border-none cursor-pointer flex  items-center justify-center font-semibold text-red-700">Choose Photo</label>
							{% endif %}
							<input type="file" id="id_profile_photo" name="profile_photo" accept="image/*" class="hidden" onchange="showPreview(this)">
						</div>
						{% else %}
						{{ field }}
						{% endif %}
						{% if field.errors %}
						<div class="text-red-500 text-sm mt-1 font-semibold">
							{% for error in field.errors %}
							{{ error }}
							{% endfor %}
						</div>
						{% endif %}
					</div>
					{% endfor %}
					<div class="mt-5 flex justify-center">
						<button type="submit" class="relative w-full border-0 py-1.5 items-center justify-center bg-gradient-to-r from-purple-500 to-blue-500 hover:from-purple-600 hover:to-blue-600 focus:outline-none focus:ring focus:ring-purple-300 active:bg-blue-700 rounded-full text-white font-semibold shadow-md transition duration-300 ease-in-out transform hover:scale-105">Update Profile</button>
					</div>
				</form>
				<p class="mt-5 mb-12 text-center text-sm text-gray-500">
					Back to
					<a href="/" class="font-semibold text-indigo-600 hover:text-indigo-500">Dashboard</a>
				</p>
			</div>	
			
		</div>
		<script src="{% static 'appoint_app/js/profile_photo.js' %}"></script>
		<script src="{% static 'appoint_app/js/register_patient.js' %}"></script>
	</body>
</html>
{% endif %}